server:
  http2:
    enabled: true
app:
  datasource:
    mongodb:
      uri: mongodb://myappuser:Pm3RVFPW@spring-grpc-app-docdb-cluster.cluster-ca9u6iqrbuz0.ap-northeast-1.docdb.amazonaws.com:27017/main?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
grpc:
  enable-reflection: true
