name: Test with Gradle
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout submodule
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #      - name: git submodule update
      #        run: git submodule update --recursive
      #      - name: generateProto
      #        run: ./gradlew generateProto
      - name: ktlint check
        run: ./gradlew ktlintCheck
      - name: start docker
        run: docker-compose up -d
      - name: Test with Gradle
        run: ./gradlew clean generateProto test